### ISSUE TITLE
Update versions of io.jsonwebtoken

### ISSUE THREAD

**Issue by artemik** [voximplant/apiclient-java#3]
Update versions of io.jsonwebtoken dependencies. The current ones are 4 years old and cause a conflict with another frameworks, therefore requiring downgrade. The newer version can't be forced, because the function calls are incompatible.

**Comment by artemik** [comment]
@nosovm ^

**Comment by artemik** [comment]
@nosovm @NikolasMelui Is this library still maintained?

**Comment by NikolasMelui** [comment]
@artemik Hi there! Thx for the issue! 👍 
Yeap, the library is maintained and the io.jsonwebtoken dependencies will be updated in the next version of the package.

**Comment by NikolasMelui** [comment]
The job is done, 
https://github.com/voximplant/apiclient-java/commit/2ee62382366e8c226800d57e74b47a178b23a560
The issue will be closed.

**Comment by artemik** [comment]
That was fast, thanks! @NikolasMelui
